Error executing the script. Error: Traceback (most recent call last):
  File "D:\PYT\FLASK 2 auto\TAKE 57 IANA get\analyzer.py", line 638, in <module>
    service_df = pd.read_csv("service.csv").drop_duplicates(subset='Port Number')
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ABProgram Files\Python\Lib\site-packages\pandas\io\parsers\readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ABProgram Files\Python\Lib\site-packages\pandas\io\parsers\readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ABProgram Files\Python\Lib\site-packages\pandas\io\parsers\readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ABProgram Files\Python\Lib\site-packages\pandas\io\parsers\readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "D:\ABProgram Files\Python\Lib\site-packages\pandas\io\common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'service.csv'
